### PR TITLE
Add exit function to calculator.

### PR DESCRIPTION
**Pull request by playsamay4**
Edit if necessary.

I just added an entry that will detect whether someone types "Exit" or "Quit", then it will execute the Main function, bringing them back to the command line. #1

### CODE REVIEW

**Comment by ingenSoftware** [comment]
The else if at the bottom is missing, so all input will just exit the program.

**Comment by playsamay4** [comment]
Whoops, fixing right now.

**Review by ingenSoftware — CHANGES_REQUESTED** [review]
Rename else if to else on line 71.

**Comment by ingenSoftware** [comment]
This function will be added by the team.

**Pull request closed without merging**
